// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV1zoE81PYx5jx2E97BT6TubGbIPRek2Y',
    appId: '1:217441105669:web:76963c9e2499ae7e12a96c',
    messagingSenderId: '217441105669',
    projectId: 'sporty-database',
    authDomain: 'sporty-database.firebaseapp.com',
    storageBucket: 'sporty-database.appspot.com',
    measurementId: 'G-189Z357LNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX_xBRfLLqUSVggODuznuIhwvskomuVv4',
    appId: '1:217441105669:android:1932a00d97b534af12a96c',
    messagingSenderId: '217441105669',
    projectId: 'sporty-database',
    storageBucket: 'sporty-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCaB5tQZeoTMOqgfUwknDA_7bBythnqJU',
    appId: '1:217441105669:ios:73e50473b78faab312a96c',
    messagingSenderId: '217441105669',
    projectId: 'sporty-database',
    storageBucket: 'sporty-database.appspot.com',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCaB5tQZeoTMOqgfUwknDA_7bBythnqJU',
    appId: '1:217441105669:ios:d94a23fe6c03614212a96c',
    messagingSenderId: '217441105669',
    projectId: 'sporty-database',
    storageBucket: 'sporty-database.appspot.com',
    iosBundleId: 'com.example.fyp.RunnerTests',
  );
}
